// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ7tJMANu4GeSIk_t6O0ao2uYJRMEWuNQ',
    appId: '1:861499445565:web:ce387572705c5e2280b554',
    messagingSenderId: '861499445565',
    projectId: 'absensi-acara',
    authDomain: 'absensi-acara.firebaseapp.com',
    storageBucket: 'absensi-acara.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMhYztXd8oPPQRgjEexDkCfv943-NyVxE',
    appId: '1:861499445565:android:a6f73043d6ceb84980b554',
    messagingSenderId: '861499445565',
    projectId: 'absensi-acara',
    storageBucket: 'absensi-acara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1MsSUs63bVC9J41IliOlsfGyKArbftlY',
    appId: '1:861499445565:ios:de92b9d8b70c207680b554',
    messagingSenderId: '861499445565',
    projectId: 'absensi-acara',
    storageBucket: 'absensi-acara.firebasestorage.app',
    iosBundleId: 'com.example.absensiAcara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1MsSUs63bVC9J41IliOlsfGyKArbftlY',
    appId: '1:861499445565:ios:de92b9d8b70c207680b554',
    messagingSenderId: '861499445565',
    projectId: 'absensi-acara',
    storageBucket: 'absensi-acara.firebasestorage.app',
    iosBundleId: 'com.example.absensiAcara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ7tJMANu4GeSIk_t6O0ao2uYJRMEWuNQ',
    appId: '1:861499445565:web:afbbaf33d368bf0080b554',
    messagingSenderId: '861499445565',
    projectId: 'absensi-acara',
    authDomain: 'absensi-acara.firebaseapp.com',
    storageBucket: 'absensi-acara.firebasestorage.app',
  );

}